version: '3.8'

services:
  bot:
    build:
      context: ./
      dockerfile: ./apps/bot/Dockerfile
    env_file:
      - ./.env
    volumes:
      - logs:/app/logs
      - database:/app/database

  trackers:
    build:
      context: ./
      dockerfile: ./apps/trackers/Dockerfile
    env_file:
      - ./.env
    volumes:
      - logs:/app/logs
      - database:/app/database

  utils:
    build:
      context: ./
      dockerfile: ./apps/utils/Dockerfile
    env_file:
      - ./.env
    volumes:
      - logs:/app/logs
      - database:/app/database

  website:
    build:
      context: ./
      dockerfile: ./apps/website/Dockerfile
    env_file:
      - ./.env
    volumes:
      - logs:/app/logs
      - database:/app/database
    ports:
      - "${WEBSITE_PORT}:443"


volumes:
  database:
  logs:
