services:
  bot:
    build:
      context: ./
      dockerfile: ./apps/bot/Dockerfile
    env_file:
      - ./.env
    volumes:
      - logs:/app/logs
      - database:/app/database
    restart: unless-stopped

  trackers:
    build:
      context: ./
      dockerfile: ./apps/trackers/Dockerfile
    env_file:
      - ./.env
    volumes:
      - logs:/app/logs
      - database:/app/database
    restart: unless-stopped

  utils:
    build:
      context: ./
      dockerfile: ./apps/utils/Dockerfile
    env_file:
      - ./.env
    volumes:
      - logs:/app/logs
      - database:/app/database
    restart: unless-stopped

  website:
    build:
      context: ./
      dockerfile: ./apps/website/Dockerfile
      target: runner
    env_file:
      - ./.env
    volumes:
      - logs:/app/logs
      - database:/app/database
    ports:
      - "${WEBSITE_PORT}:443"
    restart: unless-stopped


volumes:
  database:
  logs:
