name: Run Python Tests
permissions:
  contents: read
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v5
        with:
          python-version: 3.11.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r statalib/requirements.txt
      - name: Run tests
        run: python3 run_tests.py
        env:
          ENVIRONMENT: development
